// <auto-generated />
namespace WebAppVet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class delete_roomType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delete_roomType));
        
        string IMigrationMetadata.Id
        {
            get { return "201906301530290_delete_roomType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
