// <auto-generated />
namespace WebAppVet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_Product : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Product));
        
        string IMigrationMetadata.Id
        {
            get { return "201906231732582_add_Product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
