/* SELECCIONAR TODOS LOS TURNOS ACTIVOS */
SELECT * FROM Appointments AS A WHERE A.State = 0

/* SELECCIONAR TODOS LOS TURNOS ATENDIDOS */
SELECT * FROM Appointments AS A WHERE A.State = 1

/* SELECCIONAR TODOS LOS TURNOS CANCELADOS */
SELECT * FROM Appointments AS A WHERE A.State = 2

/* BUSCAR TODOS LOS CLIENTES CON EL NOMBRE CARLOS*/
SELECT * FROM Clients AS C WHERE C.Name = 'Carlos'
